name: Check Notice
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install axios
        run: npm install axios

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # 파일이 없으면 빈 상태({})로 미리 만들어둡니다.
          if [ ! -f last_ids.json ]; then echo "{}" > last_ids.json; fi
          node index.js

      - name: Force Push ID
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 파일이 존재할 때만 git add를 실행합니다.
          if [ -f last_ids.json ]; then
            git add last_ids.json
            if [ -n "$(git status --porcelain last_ids.json)" ]; then
              git commit -m "Update last notice IDs"
              git push --force origin main
            else
              echo "변경 사항 없음"
            fi
          else
            echo "저장할 파일이 없습니다."
          fi
